test: trying out reviewdog

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -25,33 +25,58 @@ stages:
     paths:
       - vendor/
 
-# PHP CodeSniffer checks
-test:phpcs:
+test:phpcs:reviewdog:
   stage: test
   extends: .setup_php
   rules:
     - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
     - when: never
+
+  before_script:
+    # Install reviewdog binary
+    - curl -sSfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b /usr/local/bin
+
   script:
-    - | # Multiline script
-      set +e
-      vendor/bin/phpcs -q
-      PHPCS_EXIT=$?
-      set -e
+    - |
+      vendor/bin/phpcs --report=checkstyle \
+      | reviewdog -f=checkstyle \
+          -name="PHPCS" \
+          -reporter=gitlab-mr-discussion \
+          -filter-mode=nofilter \
+          -level=warning \
+          -fail-level=any
+  variables:
+    REVIEWDOG_GITLAB_API_SERVER: "$CI_SERVER_URL/api/v4"
+    REVIEWDOG_GITLAB_API_TOKEN: "$REVIEWDOG_GITLAB_API_TOKEN"
 
-      if [ "$PHPCS_EXIT" -ne 0 ]; then
-        echo "⚠️  PHPCS found errors, generating reports..."
-        vendor/bin/phpcs -q \
-          --report=full --report-file=phpcs-report.txt \
-          --report-checkstyle=phpcs-checkstyle.xml
-      else
-        echo "✅ PHPCS passed without errors."
-      fi
-
-      exit $PHPCS_EXIT
-  artifacts:
-    when: on_failure
-    paths:
-      - phpcs-report.txt
-      - phpcs-checkstyle.xml
-    expire_in: 1 week
+#
+## PHP CodeSniffer checks
+#test:phpcs:
+#  stage: test
+#  extends: .setup_php
+#  rules:
+#    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
+#    - when: never
+#  script:
+#    - | # Multiline script
+#      set +e
+#      vendor/bin/phpcs -q
+#      PHPCS_EXIT=$?
+#      set -e
+#
+#      if [ "$PHPCS_EXIT" -ne 0 ]; then
+#        echo "⚠️  PHPCS found errors, generating reports..."
+#        vendor/bin/phpcs -q \
+#          --report=full --report-file=phpcs-report.txt \
+#          --report-checkstyle=phpcs-checkstyle.xml
+#      else
+#        echo "✅ PHPCS passed without errors."
+#      fi
+#
+#      exit $PHPCS_EXIT
+#  artifacts:
+#    when: on_failure
+#    paths:
+#      - phpcs-report.txt
+#      - phpcs-checkstyle.xml
+#    expire_in: 1 week
